name: Deploy to DEV
on:
  push:
    branches:
      # - UAT
      - develop
jobs:
  build:
    name: Generate Build and Deploy to DEV
    # environment: PROD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node Env
        uses: actions/setup-node@v3
        with:
          node-version: 21.1.0

      - name: Copy .env file
        env:
          ENV_FILE_CONTENT: ${{ secrets.env }}
        run: echo "$ENV_FILE_CONTENT" > .env
          ls -l .env
          echo "Printing .env content:"
          cat .env

      - name: Generate React Build
        run: |
          yarn install
          yarn build

      - name: Show PWD
        run: |
          echo "Current Working Directory:" 
          pwd

      - name: Create Directory
        run: mkdir my_directory

      - name: List Contents
        run: |
          echo "Contents of the current directory (in reverse order):"
           ls -lr

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY_GLA_DEV }}
          REMOTE_HOST: ${{ secrets.HOST_DNS_GLA_DEV }}
          REMOTE_USER: ${{ secrets.USERNAME_GLA_DEV }}

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY_GLA_DEV }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Add the SSH key to the known_hosts file (replace hostname with your actual hostname)
          ssh-keyscan -H ${{ secrets.HOST_DNS_GLA_DEV }} >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: |
          rsync -avz -e "ssh -i ~/.ssh/id_rsa" ./dist/ ${{ secrets.USERNAME_GLA_DEV }}@${{ secrets.HOST_DNS_GLA_DEV }}:/var/www/alt-gla-dev.uniteframework.io/public

      - name: Copy to server dist folder
        run: |
          sshpass -p '${{ secrets.EC2_SSH_KEY_GLA_DEV  }}' ssh -v -o StrictHostKeyChecking=no ${{ secrets.USERNAME_GLA_DEV  }}@${{ secrets.HOST_DNS_GLA_DEV  }} <<'ENDSSH'
          cd /home/prasad/gla-player-dist/
          ./deploy.sh
          ENDSSH
      # - name: Copy Package
      #   run: |
      #     sh ./scripts/pack-prod-build.sh
      #     rsync shiksha-ui.tar ${{ secrets.USERNAME_GLA_DEV }}@${{ secrets.HOST_DNS_GLA_DEV }}:/var/www/alt-gla-dev.uniteframework.io/shiksha-ui.tar

      # - name: Deploy
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.HOST_DNS_GLA_DEV }}
      #     username: ${{ secrets.USERNAME_GLA_DEV }}
      #     key: ${{ secrets.EC2_SSH_KEY_GLA_DEV }}
      #     script: |
      #       cd /var/www/alt-gla-dev.uniteframework.io/public
      #       rm -rf *
      #       cp ../shiksha-ui.tar ./
      #       tar -xvf shiksha-ui.tar .

  #     - name: Notify on Slack channel
  #       uses: iRoachie/slack-github-actions@v2.3.2
  #       env:
  #         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_NEWALTV1_URL }}
  #       with:
  #         status: ${{ job.status }}
  #       if: ${{ always() }}
